# Generated by Django 2.1.3 on 2018-11-11 23:16

import alerts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=5, verbose_name='Currency')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('under', models.BooleanField(default=True, verbose_name='Under')),
                ('cutoff_value', models.IntegerField(validators=[alerts.models.validate_number], verbose_name='Cutoff Value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
            },
        ),
    ]
